version: '3.8'
volumes:
  prometheus_data: {}

networks:
  front-tier:
  back-tier:


services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./.HASS_LL_TOKEN:/etc/prometheus/HASS_LL_TOKEN
      - prometheus_data:/prometheus
    command:
      - '--enable-feature=expand-external-labels'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - back-tier
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: '472'
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana.datasource.yml:/etc/grafana/provisioning/datasource.yml
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,marcusolsson-dynamictext-panel
      #- GF_AUTH_ANONYMOUS_ENABLED=true #added
      #- GF_SECURITY_COOKIE_SAMESITE=none #added
      - GF_SECURITY_ALLOW_EMBEDDING=true #added
    networks:
      - back-tier
      - front-tier
  home-assistant:
    container_name: hass
    image: homeassistant/home-assistant
    ports:
      - 8000:8123
    volumes:
      #- ./hass_configuration.yml:/config/configuration.yaml
      - ./hass-data:/config
      - ./hass-media:/data/media:ro
    privileged: true
    networks:
      - back-tier
      - front-tier
    restart: always
    depends_on:
      - grafana
  cadvisor:
    container_name: cadvisor
    # metrics about containers
    image: gcr.io/cadvisor/cadvisor-arm64:v0.46.0
    volumes:
      #- /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8585:8080
    command:
      - '--housekeeping_interval=15s'
      - '--docker_only=true'
    restart: always
    networks:
      - back-tier
  jetson_collector:
    build:
      context: ./jetson_collector
      dockerfile: jetson_collector.Dockerfile
    container_name: jetson_collector
    restart: always
    volumes:
      - /run/jtop.sock:/run/jtop.sock
    environment:
      - COLLECT_TIME=5
      - COLLECTOR_PORT=3030
    networks:
      - back-tier
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Paris
    env_file:
      - ./.swag.env
    volumes:
      - ./swag-data:/config
    ports:
      - 443:443
    restart: unless-stopped
    networks:
      - front-tier
      - back-tier
  # nginx_prom_exporter:
  #   container_name: nginx_prom_exporter
  #   image: nginx/nginx-prometheus-exporter:0.10.0
  #   command:
  #     - '-nginx.scrape-uri=https://grafana.curiousdolphin.duckdns.org:16666/nginx_status'
  #   networks:
  #     - back-tier

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - ${LOCAL_IP}:53:53/tcp #https://github.com/sameersbn/docker-bind/issues/65
      - ${LOCAL_IP}:53:53/udp
      - "${LOCAL_IP}:67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - 8181:80/tcp
    environment:
      TZ: 'Europe/Rome'
      WEBPASSWORD: ${PIHOLE_WEB_PWD}
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      # Volumes store your data between container upgrades
    volumes:
      - './pihole-data/pihole:/etc/pihole'
      - './pihole-data/dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    networks:
      - front-tier
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      #- "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data/:/mosquitto/data
    restart: always
    ports:
      - 1883:1883
    networks:
      - back-tier
